### ISSUE TITLE
Take down InvisibleMan-XRay v2.3.2!

### ISSUE THREAD

**Issue by pps83** [InvisibleManVPN/InvisibleMan-XRayClient#132] opened 2024-09-21 09:22 UTC
You should take down [InvisibleMan-XRay v2.3.2](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/releases/tag/v2.3.2) as it's broken. It simply does not work! Works once, after that it stops working.

Try to disconnect and connect again: IT DOES NOT WORK!

**Comment by InvisibleManVPN** [comment] 2024-09-21 09:57
Hello @pps83,
That's not the solution!
Currently, many users already download the latest version and can work with it.
Can you give me more description about your problem? In which mode you can't connect? Did you check all files extracted correctly? Provide me more description and we can investigate the problem.

**Comment by pps83** [comment] 2024-09-21 18:07
It's the same problem described [here](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/issues/126).
x64 win11 pro, with TUN interface. It works only once. If  you disconnect, and then reconnect client shows as if it's all connected and working, while it's actually NOT connected to any vpn. That's why you should take done this version, as it's broken.

I did install it properly, no need to ask. I had it installed on multiple PCs, all had the same issue. I rolled back to previous one [InvisibleMan-XRay v2.1.2](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/releases/tag/v2.1.2) and it has no issues.

**Comment by InvisibleManVPN** [comment] 2024-09-22 09:56
@pps83 I need to investigate all the possibilities. Thus I ask about them. So be patient and answer them. OK, so based on your test we know the problem is not related to the Invisible Man TUN and we need to find the problem in the Invisible Man XRay app. Also, the problem occurs in some scenarios and some people are faced with this issue. Let me check in details.

**Comment by Budi8888** [comment] 2024-10-11 12:46
Just trying your service before pay - no result.
![Poblem with trial 111024](https://github.com/user-attachments/assets/604aa6ae-69ba-4387-ad06-b2a3aadd8eaa)

**Comment by InvisibleManVPN** [comment] 2024-10-16 09:27
Hello @Budi8888
I think the main problem is that you put the app in a non-English directory. This is one of the bad problems in this app, but I fixed it and it will be OK from the upcoming release (see [this](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/pull/139)). For now, just put the app in a fully-English directory and then try to use.

**Comment by InvisibleManVPN** [comment] 2024-10-23 08:10
Referring to the #126 issue, the problem is related to the TUN service and it will fixed now. So, you need to wait for the next release of **Invisible Man XRay** or update the **Invisible Man TUN** to the latest version that has already been published ([InvisibleMan-TUN v0.3.5](https://github.com/InvisibleManVPN/InvisibleMan-TUN/releases/tag/v0.3.5))

**Closed by InvisibleManVPN** 2024-10-23 08:10 UTC
Labels: bug
